### ISSUE TITLE
Option to suppress cleaning "bower_components"

### ISSUE THREAD

**Issue by chrylis** [dbashford/mimosa-bower#45]
I'm trying to track a problem with a package that doesn't include all its main files in `main`, and I would like to be able to tell Mimosa not to blow away the temporary `bower_components` directory so that I can inspect exactly what it's looking at.

**Comment by dbashford** [comment]
`bower.bowerDir.clean` ?

**Comment by dbashford** [comment]
I believe this is what you need: https://github.com/dbashford/mimosa-bower#bowerbowerdirclean-boolean

**Comment by chrylis** [comment]
Aha, I just couldn't find it. I thought it would be exposed as a command-line option.

**Comment by dbashford** [comment]
@chrylis I stumbled across the thread on cujo issues list.  If you are having any trouble, either with getting what you need out of bower or figuring out what is happening with the requirejs stuff, let me know.  If you set up a super simple bare bones github project exhibiting any issues I can probably help you work through them.

**Comment by chrylis** [comment]
There are a few issues going on, and I haven't taken the time to track them all down. The RequireJS problems have to do with the fact that modules go under `vendor/modulename`, and then other library modules are trying to import, e.g., just `Bacon` instead of `vendor/Bacon`, and then overriding the `paths` gets things out of whack with relative module includes...

**Comment by dbashford** [comment]
Try this: https://github.com/dbashford/mimosa-npm-web-dependencies

I tossed that together yesterday.  Been wanting to do something like it for awhile.  Tried it with a half dozen libraries and it does the trick.

Need to update the docs, but that module will not `npm install` anything for you, but it will inject any installed libraries into your app.

**Comment by chrylis** [comment]
That looks like it may very well have some of the functionality I need, and I'll poke at it as soon as I can manage.

**Comment by dbashford** [comment]
Any chance you had a chance to try it out?  Would be curious...

**Comment by chrylis** [comment]
Yes, this behaves as expected. Would be nice to be able to specify this on the command line for a particular run (I'm accustomed to Java's `-Dproperty.name=value`), but that's a general low-priority improvement to the Mimosa shell.

**Comment by dbashford** [comment]
Do you mean installing like... `mimosa npmweb someLibrary@1.0.0`?

I rather not replace/duplicate what is, in the case, best performed with NPM.

**Comment by chrylis** [comment]
Never mind, I apparently overlooked your intervening comment, which was addressed at the underlying task and not the specific issue of keeping the Bower directory. I'm not certain what additional benefits `npmweb` offers over using Bower for the same(?) dependencies.

**Comment by dbashford** [comment]
The general populace will take awhile to catch up, but the thought leaders are moving away from Bower.  NPM is winning.  What you get from `npmweb` is something that manages issues like the one illuminated by the `when` problem without needing reams of config.  With bower, because the `bower.json` can't always be relied upon, you are left having to tell mimosa all the files that are needed.  With `npmweb` the entire component is just browserified up and you get what you need.

**Comment by chrylis** [comment]
I'm generally aware of the trend against Bower because of issues regarding dependency management, and so I've picked NPM versions when both were visibly available, but unfortunately I couldn't find some of our bits in NPM. I'll put "migrate to `npmweb`" on our medium-term plans.
